<?php
/**
 * @file
 * Module file for OSU Migrations
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_prepare_row().
 */
function osu_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  switch ($migration->id()) {
    case 'd7_field_instance':
      if ($row->getSource()['entity_type'] !== 'node') {
        return FALSE;
      }
      dump($row->getSource()['entity_type']);
      break;
  }
}
